CREATE database rentalMovieDB;

use rentalMovieDB;

create table movies(
movie_id integer auto_increment,
movie_title varchar(100) not null,
movie_runtime varchar(100) not null,
movie_classification varchar(10) not null,
movie_release varchar(10) not null,
movie_genre varchar(100) not null,
movie_director varchar(50) not null,
movie_actors varchar(200) not null,
movie_synopsis varchar(500) not null,
movie_imageUrl varchar(1000) not null,
movie_image2Url varchar(1000) not null,
movie_videoUrl varchar(1000) not null,
PRIMARY KEY(movie_id)
);

INSERT INTO movies(movie_title,movie_runtime,movie_classification,movie_release,movie_genre,movie_director,movie_actors,movie_synopsis,movie_imageUrl,movie_image2Url,movie_videoUrl)
VALUES
('Fast X','2h 21m','12A','2023','Action, Adventure, Crime','Louis Leterrier','Vin Diesel, Jason Momoa, Alan Ritchson, Rita Moreno, Michelle Rodriguez, Brie Larson','Over many missions and against impossible odds, Dom Toretto and his family have outsmarted and outdriven every foe in their path. Now, they must confront the most lethal opponent they have ever faced. Fueled by revenge, a terrifying threat emerges from the shadows of the past to shatter Doms world and destroy everything -- and everyone -- he loves.','https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aa454069-1f38-4db1-a9e3-75d6b00c42e8/dfys5s9-96c68a4a-5d6a-4fe2-8815-9db1d2f4c151.jpg/v1/fit/w_750,h_1072,q_70,strp/fast_x_poster_by_akithefull_dfys5s9-375w-2x.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTgyOSIsInBhdGgiOiJcL2ZcL2FhNDU0MDY5LTFmMzgtNGRiMS1hOWUzLTc1ZDZiMDBjNDJlOFwvZGZ5czVzOS05NmM2OGE0YS01ZDZhLTRmZTItODgxNS05ZGIxZDJmNGMxNTEuanBnIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.LQfa9utoB2HvRurkB7bglXC8MQKWHJvSkaeATF6r9mU','https://www.cnet.com/a/img/resize/e40db3b1ecae8c7de688981520ac2c3d8c7c9617/hub/2023/08/16/23d96691-7b64-4113-81f8-71f8430f9aff/fast-x-peacock.jpg?auto=webp&width=1200','https://www.youtube.com/watch?v=32RAq6JzY-w'),
('Anyone But You','1h 43m','15','2023','Comedy, Romance','Will Gluck','Sydney Sweeney, Glen Powell, Alexandra Shipp','Despite an amazing first date, Bea and Bens initial attraction quickly turns sour. However, when they unexpectedly find themselves at a destination wedding in Australia, they pretend to be the perfect couple to keep up appearances.','https://eastside-online.org/wp-content/uploads/2024/01/anyone-but-you-predictions-v0-e1cbqy6cm23c1.webp','https://media.vanityfair.com/photos/65844a4cb644f728430cf119/master/w_2560%2Cc_limit/anyone-but-you-review.jpg','https://www.youtube.com/watch?v=UtjH6Sk7Gxs'),
('Aquaman and the Lost Kingdom','2h 4m','12A','2023','Action, Adventure, FantasySci-Fi','James Wan','Jason Momoa, Patrick Wilson, Amber Heard, Yahya Abdul-Mateen II, Randall Park, Dolph Lundgren, Temuera Morrison, Martin Short, Nicole Kidman','Black Manta seeks revenge on Aquaman for his fathers death. Wielding the Black Tridents power, he becomes a formidable foe. To defend Atlantis, Aquaman forges an alliance with his imprisoned brother. They must protect the kingdom.','https://cdn.europosters.eu/image/1300/posters/aquaman-and-the-lost-kingdom-tempest-i198189.jpg','https://m.media-amazon.com/images/M/MV5BNjMxM2Y4NjMtNmE4OC00NDRkLWJlZGItNzI2ZGYxMWQ2MzYwXkEyXkFqcGdeQWFybm8@._V1_QL75_UX500_CR0,0,500,281_.jpg','https://www.youtube.com/embed/FV3bqvOHRQo'),
('The Hunger Games','2h 37m','12A','2023','Action, Adventure, Drama','Francis Lawrence','Rachel Zegler, Tom Blyth, Viola Davis','Coriolanus Snow mentors and develops feelings for the female District 12 tribute during the 10th Hunger Games.','https://image.tmdb.org/t/p/original/9cbeNkXx0OTC9pg30OZIWRi9HmL.jpg','https://m.media-amazon.com/images/M/MV5BZDJmNDIxZjktYjA3YS00ZDQzLWJmMGYtOTBkY2FjOGY3ZDZjXkEyXkFqcGdeQWFybm8@._V1_QL75_UX500_CR0,0,500,281_.jpg','https://www.youtube.com/embed/NxW_X4kzeus'),
('Oppenheimer','3h','15','2023','Biography, Drama, History','Christopher Nolan','Cillian Murphy, Emily Blunt, Matt Damon','The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.','https://upload.wikimedia.org/wikipedia/fi/thumb/8/84/Oppenheimer-poster.jpg/800px-Oppenheimer-poster.jpg','https://upload.wikimedia.org/wikipedia/it/a/ab/Oppenheimer_%28film%29.png','https://www.youtube.com/watch?v=uYPbbksJxIg'),
('Saltburn','2h 11m','15','2023','Comedy, Drama, Thriller','Emerald Fennell','Barry Keoghan, Jacob Elordi, Rosamund Pike','A student at Oxford University finds himself drawn into the world of a charming and aristocratic classmate, who invites him to his eccentric familys sprawling estate for a summer never to be forgotten.','https://cdn.cinematerial.com/p/297x/wxxe27sa/saltburn-movie-poster-md.jpg?v=1698458958','https://www.irishtimes.com/resizer/7Ms12LgP8RyH9lHkRObFimEk5v0=/1600x1200/filters:format(jpg):quality(70):focal(1680x755:1690x765)/cloudfront-eu-central-1.images.arcpublishing.com/irishtimes/2K3RH27C4FB75JRW4XFIGDK2QE.jpg','https://www.youtube.com/watch?v=lALMdJf6UUE'),
('Wonka','1h 56m','PG','2023','Adventure, Comedy, Family','Paul King','Timothée Chalamet, Gustave Die, Murray McArthur','With dreams of opening a shop in a city renowned for its chocolate, a young and poor Willy Wonka discovers that the industry is run by a cartel of greedy chocolatiers.','https://www.odeoncinemas.ie/media/yoxan4jg/gb_wonka_insta_vert_character_art_timothee_chalamet_1638x2048_intl-1.jpg','https://www.odeoncinemas.ie/media/utxc2y5n/rev-1-won-cc-0001r_high_res_jpeg-1.jpg','https://www.youtube.com/watch?v=EJoom2F-7nI'),
('Killers of the Flower Moon','3h 26m','15','2023','Crime, Drama, History','Martin Scorsese','Leonardo DiCaprio, Robert De Niro, Lily Gladstone','When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one - until the FBI steps in to unravel the mystery.','https://birchbarkbooks.com/cdn/shop/files/killers-of-the-flower-moon-ya.jpg?v=1690496218','https://upload.wikimedia.org/wikipedia/it/thumb/b/bf/Killers_of_the_Flower_Moon.jpg/800px-Killers_of_the_Flower_Moon.jpg','https://www.youtube.com/watch?v=EP34Yoxs3FQ'),
('Joker','2h 2m','15','2019','Crime, Drama, Thriller','Todd Phillips','Joaquin Phoenix, Robert De Niro, Zazie Beetz','During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.','https://artofthemovies.co.uk/cdn/shop/products/IMG_7868_1024x1024@2x.jpg?v=1646737198','https://cdn.vox-cdn.com/thumbor/WAVESAmwUdxWYZKuUr48zpid3nA=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/19187243/joker2.jpg','https://www.youtube.com/watch?v=t433PEQGErc'),
('The Godfather','2h 55m','15','1972','Crime, Drama','Francis Ford Coppola','Marlon Brando, Al Pacino, James Caan','The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.','https://media.posterlounge.com/img/products/710000/707663/707663_poster.jpg','https://www.okcmoa.com/wp-content/uploads/2022/08/HT-godfatrher-jef-170308_16x9_1600-1340x586.jpg','https://www.youtube.com/watch?v=UaVTIH8mujA'),
('Forrest Gump','2h 22m','12','1994','Drama, Romance','Robert Zemeckis','Tom Hanks, Robin Wright, Gary Sinise','The history of the United States from the 1950s to the 70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.','https://m.media-amazon.com/images/I/81xTx-LxAPL._AC_UF894,1000_QL80_.jpg','https://www.hollywoodreporter.com/wp-content/uploads/2016/07/forrest_gump_still.jpg','https://www.youtube.com/watch?v=bLvqoHBptjg'),
('Fight Club','2h 19m','18','1999','Drama','David Fincher','Brad Pitt, Edward Norton, Meat Loaf','An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.','https://i.etsystatic.com/18242346/r/il/c9908e/2412674268/il_fullxfull.2412674268_1sgm.jpg','https://media.newyorker.com/photos/5dbafcc91b4a6700085a7a9b/1:1/w_1707,h_1708,c_limit/Baker-FightClub.jpg','https://www.youtube.com/watch?v=BdJKm16Co6M'),
('Inception','2h 28m','12A','2010','Action, Adventure, Sci-Fi','Christopher Nolan','Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page','A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.','https://i.ebayimg.com/images/g/FfsAAOSwrjNgr3rc/s-l1200.webp','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsDZu_yLlssmeWCn69_xR81yPZD3DUqdOiNdXcw_BOiE0Gbkdvyfa97Cryufm-PGZUfY4&usqp=CAU','https://www.youtube.com/watch?v=YoHD9XEInc0'),
('The Matrix','2h 16m','15','1999','Action, Sci-Fi','Lana Wachowski, Lilly Wachowski','Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss','When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.','https://m.media-amazon.com/images/I/51DUmDryAvL._AC_UF894,1000_QL80_.jpg','https://img.buzzfeed.com/buzzfeed-static/complex/images/gjlwbw67beqdbqafbzfw/trinity.jpg?output-format=jpg&output-quality=auto','https://www.youtube.com/watch?v=vKQi3bBA1y8'),
('Seven','2h 7m','18','1995','Crime, Drama, Mystery','David Fincher','Morgan Freeman, Brad Pitt, Kevin Spacey','Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.','https://m.media-amazon.com/images/M/MV5BZDgyZmY5MmItY2I3Ny00NjA4LWFhNmItMGQ4ZGJhZDk5YjU3XkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg','https://dus09vr7ngt46.cloudfront.net/uploads/2017/10/09151509/seven1.jpg?height=340&width=647','https://www.youtube.com/watch?v=znmZoVkCjpI'),
('Interestellar','2h 49m','12A','2014','Adventure, Drama, Sci-Fi','Christopher Nolan','Matthew McConaughey, Anne Hathaway, Jessica Chastain','When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.','https://i.ebayimg.com/images/g/zu4AAOSw2spbJQ0J/s-l1600.jpg','https://pyxis.nymag.com/v1/imgs/64a/f38/7e691f2213742142e72e47a5ddab44e2ee-01-interstellar.2x.h473.w710.jpg','https://www.youtube.com/watch?v=zSWdZVtXT7E'),
('Saving Private Ryan','2h 49m','15','1998','Drama, War','Steven Spielberg','Tom Hanks, Matt Damon, Tom Sizemore','Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.','https://media.posterlounge.com/img/products/610000/605804/605804_poster.jpg','https://m.media-amazon.com/images/M/MV5BMWJlZWQ3NDktODc2Zi00NGY4LWI4MDMtYWQwNTUyOWVhMmQxXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_QL75_UX500_CR0,0,500,281_.jpg','https://www.youtube.com/watch?v=9CiW_DgxCnQ'),
('City of God','2h 10m','18','2002','Crime, Drama','Fernando Meirelles, Kátia Lund','Alexandre Rodrigues, Leandro Firmino, Matheus Nachtergaele','In the slums of Rio, two kids paths diverge as one struggles to become a photographer and the other a kingpin.','https://www.miramax.com/assets/City-of-God1.png','https://film-grab.com/wp-content/uploads/photo-gallery/City_of_God_009.jpg?bwg=1602064526','https://www.youtube.com/watch?v=dcUOO4Itgmw'),
('Star Wars: Episode IV - A New Hope','2h 1m','PG','1977','Action, Adventure, Fantasy','George Lucas','Mark Hamill, Harrison Ford, Carrie Fisher','Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empires world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.','https://filmlibrary.ie/cdn/shop/products/star-wars-a-new-hope-special-approval-required-poster_1024x1024.jpg?v=1605648153','https://l450v.alamy.com/450v/t2y47c/carrie-fisher-kenny-baker-star-wars-episode-iv-a-new-hope-1977-t2y47c.jpg','https://www.youtube.com/watch?v=vZ734NWnAHA'),
('Back to the Future','1h 56m','PG','1985','Adventure, Comedy, Sci-Fi','Robert Zemeckis','Michael J. Fox, Christopher Lloyd, Lea Thompson','Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.','https://cdn.europosters.eu/image/1300/posters/back-to-the-future-i152504.jpg','https://m.media-amazon.com/images/M/MV5BZGRjZDVkN2YtNGQyZi00NzkxLWJkNDAtYzNkY2M5M2M5MmUwXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_QL75_UX500_CR0,0,500,281_.jpg','https://www.youtube.com/watch?v=qvsgGtivCgs'),
('The Pianist','2h 30m','15','2002','Biography, Drama, Music','Roman Polanski','Adrien Brody, Thomas Kretschmann, Frank Finlay','During WWII, acclaimed Polish musician Wladyslaw faces various struggles as he loses contact with his family. As the situation worsens, he hides in the ruins of Warsaw in order to survive.','https://cdn.shopify.com/s/files/1/2036/5517/products/MM00321970_1024x1024.jpg?v=1694453178','https://s3.us-east-1.amazonaws.com/zweb-s3.uploads/visiontv/wp-content/uploads/2023/10/31130732/The-Pianist_06_1200.jpg','https://www.youtube.com/watch?v=BFwGqLa_oAo'),
('The Lion King','1h 29m','PG','1994','Animation, Adventure, Drama','Roger Allers, Rob Minkoff','Matthew Broderick, Jeremy Irons, James Earl Jones','Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.','https://m.media-amazon.com/images/I/61jkTiX8NuL._AC_UF894,1000_QL80_.jpg','https://cdn.kinocheck.com/i/w=480/n3l1py27p5.jpg','https://www.youtube.com/watch?v=7TavVZMewpY'),
('Casablanca','1h 42m','PG','1942','Drama, Romance, War','Michael Curtiz','Humphrey Bogart, Ingrid Bergman, Paul Henreid','A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.','https://storage.googleapis.com/pod_public/1300/145805.jpg','https://storage.googleapis.com/pod_public/1300/145805.jpg','https://www.youtube.com/watch?v=nqlROp1TIgo'),
('The Father','1h 37m','12A','2020','Drama, Mistery','Florian Zeller','Anthony Hopkins, Olivia Colman, Mark Gatiss','A man refuses all assistance from his daughter as he ages. As he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind and even the fabric of his reality.','https://media-cache.cinematerial.com/p/500x/vntmjrsh/the-father-british-movie-poster.jpg?v=1600268666','https://m.media-amazon.com/images/M/MV5BNDA5MmY1NDQtYzM5Ni00OTFlLWFlMjAtNzkxZDdlMTY3ZTUzXkEyXkFqcGdeQWFybm8@._V1_QL75_UX500_CR0,26,500,281_.jpg','https://www.youtube.com/watch?v=4TZb7YfK-JI'),
('Die Hard','2h 12m','18','1988','Action, Thriller','John Mctiernan','Bruce Willis, Alan Rickman, Bonnie Bedelia','A New York City police officer tries to save his estranged wife and several others taken hostage by terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.','https://images.squarespace-cdn.com/content/v1/64393af6c3d4da7ca1099c71/1699098658415-HQNVWWEHBOFMHWQ7SDLT/Die+Hard.png','https://images.bauerhosting.com/empire/2019/09/die-hard.jpg?ar=16%3A9&fit=crop&crop=top&auto=format&w=undefined&q=80','https://www.youtube.com/watch?v=jaJuwKCmJbY'),
('Jaws','2h 4m','12','1975','Adventure, Mystery, Thriller','Steven Spielberg','Roy Scheider, Robert Shaw, Richard Dreyfuss','When a killer shark unleashes chaos on a beach community off Cape Cod, its up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.','https://m.media-amazon.com/images/I/81KLfL7j2CL._AC_UF894,1000_QL80_.jpg','https://m.media-amazon.com/images/M/MV5BZTI1Y2I2ZTMtY2RmNy00NzUzLWFjYWItMzUxMWNmZmZjMDMzXkEyXkFqcGdeQVRoaXJkUGFydHlJbmdlc3Rpb25Xb3JrZmxvdw@@._V1_QL75_UX500_CR0,0,500,281_.jpg','https://www.youtube.com/watch?v=U1fu_sA7XhE'),
('Jurassic Park','2h 7m','PG','1993','Action, Adventure, Sci-Fi','Steven Spielberg','Sam Neill, Laura Dern, Jeff Goldblum','A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the parks cloned dinosaurs to run loose.','https://m.media-amazon.com/images/I/91XMXQCZwKL._AC_UF350,350_QL80_.jpg','https://www.intofilm.org/intofilm-production/scaledcropped/1096x548https%3A/s3-eu-west-1.amazonaws.com/images.cdn.filmclub.org/film__3877-jurassic-park--hi_res-458ae800.jpg/film__3877-jurassic-park--hi_res-458ae800.jpg','https://www.youtube.com/watch?v=E8WaFvwtphY'),
('The Exorcist','2h 2m','18','1973','Horror','William Friedkin','Ellen Burstyn, Max von Sydow, Linda Blair','When a young girl is possessed by a mysterious entity, her mother seeks the help of two Catholic priests to save her life.','https://media.posterlounge.com/img/products/510000/507754/507754_poster.jpg','https://toplist.vn/images/800px/the-exorcist-collection-my-55241.jpg','https://www.youtube.com/watch?v=YDGw1MTEe9k'),
('Ratatouille','1h 51m','PG','2007','Animation, Adventure, Comedy','Brad Bird, Jan Pinkava','Brad Garrett, Lou Romano, Patton Oswalt','A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.','https://i.ebayimg.com/images/g/qQsAAOSw--1bOR8h/s-l1600.jpg','https://www.corriere.it/methode_image/2022/01/13/Cucina/Foto%20Cucina%20-%20Trattate/Ratatouille_copertina-kuTD--590x445@Corriere-Web-Sezioni.jpg','https://www.youtube.com/watch?v=NgsQ8mVkN8w'),
('Logan','2h 17m','15','2017','Action, Drama, Sci-Fi','James Mangold','Hugh Jackman, Patrick Stewart, Dafne Keen','In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety.','https://m.media-amazon.com/images/I/51wewtpj08L._AC_UF894,1000_QL80_.jpg','https://m.media-amazon.com/images/M/MV5BMjQxNDgzMTU5M15BMl5BanBnXkFtZTgwODE3OTgxMTI@._V1_QL75_UX500_CR0,0,500,281_.jpg','https://www.youtube.com/watch?v=Div0iP65aZo'),
('Dune: Part II', '2h 47m', '12A', '2024', 'Action, Adventure', 'Francis Lawrence', 'Souheila Yacoub, Austin Butler, Timothée Chalamet, Tim Blake Nelson', 'Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.', 'https://www.dvdsreleasedates.com/posters/800/D/Dune-Part-Two-2023-movie-poster.jpg', 'https://cdn.mos.cms.futurecdn.net/VWFncKUBaF9E3v4k8QkJbf.jpg', 'https://www.youtube.com/watch?v=U2Qp5pL3ovA'),
('Godzilla x Kong', '1h 55m', '12A', '2024', 'Action', 'Adam Wingard', 'Alex Ferns, Rebecca Hall, Dan Stevens, Fala Chen, Brian Tyree Henry, Kaylee Hottle', 'The epic battle continues! Legendary Pictures’ cinematic Monsterverse follows up the explosive showdown of “Godzilla vs. Kong” with an all-new adventure that pits the almighty Kong and the fearsome Godzilla against a colossal undiscovered threat hidden within our world, challenging their very existence—and our own. “Godzilla x Kong: The New Empire” delves further into the histories of these Titans and their origins, as well as the mysteries of Skull Island and beyond.', 'https://m.media-amazon.com/images/I/711ltjnT18L._AC_UF1000,1000_QL80_.jpg', 'https://m.media-amazon.com/images/M/MV5BNjUxYmIzNWEtOTk4MC00MTUyLWE3OWEtNDY5ZGI0YmM1YmYzXkEyXkFqcGdeQVRoaXJkUGFydHlJbmdlc3Rpb25Xb3JrZmxvdw@@._V1_.jpg', 'https://www.youtube.com/watch?v=lV1OOlGwExM'),
('Inmaculate', '1h 29m', '16', '2024', 'Horror', 'Michael Mohan', 'Sydney Sweeney, Benedetta Porcaroli, Álvaro Morte, Simona Tabasco', 'Sydney Sweeney (Anyone But You, Euphoria, The White Lotus) stars as Cecilia, an American nun of devout faith, embarking on a new journey in a remote convent in the picturesque Italian countryside. Cecilias warm welcome quickly devolves into a nightmare as it becomes clear her new home harbours a sinister secret and unspeakable horrors.', 'https://m.media-amazon.com/images/M/MV5BNmYyZGQzM2YtYTY3My00NGE5LWIzMmQtMDIxMTFhMGIxZDhhXkEyXkFqcGdeQXVyMTY0Njc2MTUx._V1_FMjpg_UX1000_.jpg', 'https://www.heavenofhorror.com/wp-content/uploads/2024/01/immaculate-2024-horror-movie.jpg', 'https://www.youtube.com/watch?v=ewxS9Z-XXYo'),
('Barbie', '1h 54m', '12A', '2023', 'Adventure, Comedy, Fantasy', 'Greta Gerwig', 'Margot Robbie, Ryan Gosling, Issa Rae', 'Eccentric and individualistic, Barbie is exiled from Barbieland because of her imperfections. When her home world is in peril, Barbie returns with the knowledge that what makes her different also makes her stronger.', 'https://web-booking.lighthousegroup.ie/CDN/Image/Entity/FilmPosterGraphic/HO00000810', 'https://hips.hearstapps.com/hmg-prod/images/barbie-trailer-film-margot-robbie-646f77b0b6a30.jpg?crop=1xw:0.84375xh;center,top&resize=1200:*', 'https://www.youtube.com/watch?v=pBk4NYhWNMM'),
('Poor Things', '2h 22m', '18', '2024', 'Crime, Drama, Thriller', 'Yorgos Lanthimos', 'Willem Dafoe, Emma Stone, Christopher Abbott, Margaret Qualley, Mark Ruffalo, Jerrod Carmichael', 'When a young woman in Victorian England meets a tragic end, little did she know how much life still lay in store for her. Re-animated by her de facto guardian, the scientist Dr Goodwin Baxter, Bella Baxters mind soon becomes increasingly alive to the opportunities the world offers.', 'https://www.pearlanddean.com/wp-content/uploads/2024/01/PoorThings-17-683x1024.jpg', 'https://www.ekathimerini.com/wp-content/uploads/2023/08/poorthings_web.jpg', 'https://www.youtube.com/watch?v=ZFu7ZH4y6J4');
;
create table administrator(
admin_id integer auto_increment,
admin_name varchar(50) not null,
admin_surname varchar(50) not null,
admin_email varchar(100) not null UNIQUE,
admin_password varchar(50) not null,
PRIMARY KEY(admin_id)
);

INSERT INTO administrator(admin_name, admin_surname, admin_email, admin_password) values ('Admin', 'Student', 'elchuli3000@gmail.com', 'cct123');

create table users(
user_id integer auto_increment,
user_name varchar(50) not null,
user_surname varchar(50) not null,
user_email varchar(100) not null UNIQUE,
user_password varchar(50) not null,
PRIMARY KEY(user_id)
);

create table myBookings(
book_id integer auto_increment,
user_id integer not null,
movie_id integer not null,
movie_time varchar(20) not null,
ticket_amount varchar(20) not null,
cinema varchar(20) not null,
PRIMARY KEY(book_id),
FOREIGN KEY(user_id) references users(user_id) on delete cascade,
FOREIGN KEY(movie_id) references movies(movie_id) on delete cascade
);

